[supervisord]
nodaemon=true
user=user
logfile=/tmp/supervisord.log
pidfile=/tmp/supervisord.pid

[program:redis]
command=redis-server --port 6379 --dir /tmp --dbfilename dump.rdb
autostart=true
autorestart=true
stdout_logfile=/tmp/redis.stdout.log
stderr_logfile=/tmp/redis.stderr.log

[program:celery]
command=celery -A app.celery worker --loglevel=info
directory=/app
autostart=true
autorestart=true
stdout_logfile=/tmp/celery.stdout.log
stderr_logfile=/tmp/celery.stderr.log

[program:flask]
command=python app.py
directory=/app
autostart=true
autorestart=true
stdout_logfile=/tmp/flask.stdout.log
stderr_logfile=/tmp/flask.stderr.log
